### PR TITLE
Added function to remember the muted websites between browser sessions

### PR DESCRIPTION
**Pull request by revoconner**
Not sure if it will work, but if it does, please publish it, so I can use.

### CODE REVIEW

**Comment by pkrasicki** [comment]
Did it not work? I haven't looked much into this yet, but you probably need to add an additional permission to `manifest.json` (addons need to request permissions for every feature they use, so that the user knows what the addon does when they install it) and it looks like you haven't done that. [From the docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage):
>To use this API you need to include the "storage" permission in your manifest.json file.

To build the addon yourself, you can either run the `build.sh` script or just manually put the following files (and one folder) into a .zip file: `background.js, manifest.json, icons, LICENSE`.

Then to test it, in Firefox go to `about:debugging` in the URL bar, go to `This Firefox` section and click `Load Temporary Add-on...` and select your .zip file. You can then go to the Extensions page and enable it there. When you restart Firefox, the addon will disappear. If you want to keep using it permanently, I think you would have to publish your version to the addon store (feel free to do that). I should probably add those instructions to the readme.

**Comment by revoconner** [comment]
Hey sorry I closed the pull request because of the bug you said. I have now made this extension work (had to test it on developers firefox). I also published it with the functionality because apparently the only way to install add ons in firefox is from the store, you cant do it from a file. I have credited you as well. 
https://github.com/revoconner/firefox-mute-site
The current version of the add on is here https://addons.mozilla.org/en-US/firefox/addon/mute-domains-until-unmuted/ 
and has a list of all muted domains. if you want to incorporate this change into your repo I will create another request and delete my add on from the store once yours gets live. (I do need the function working on my browser).

**Comment by pkrasicki** [comment]
No problem, I'm glad that it worked for you. Thanks for crediting me on your addon. I will probably do this feature a little differently. I think I will add it as an optional setting, like I mentioned in your issue #3.

You don't have to delete your addon if it's useful to you. It might be useful to other people too. You can also look into those addons, which probably have the same functionality:
https://addons.mozilla.org/en-US/firefox/addon/mutelinks/

https://addons.mozilla.org/en-US/firefox/addon/mute-sites-by-default/

**Comment by revoconner** [comment]
got it, thanks! this is the default behavior in chromium so its kind of helpful to have the exact copy in firefox. I will keep my end of things updated when it needs to be

**Pull request closed without merging**
